# -*- coding: utf-8 -*-
"""Conheça o Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

idade = int(input("Digite sua idade: "))
carteira = bool(input("Você tem carteira de estudante? (s/n): "))

if idade < 12:
  print("Sua passagem não é permitida neste cinema.")
elif idade >= 12 and carteira == True:
  print("Você pode entrar na sala de cinema por meia-passagem.")
elif idade >= 12 and carteira == False:
  print("Você pode entrar na sala de cinema com o valor total.")