# -*- coding: utf-8 -*-
"""Conheça o Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

nota = int(input("Digite a sua nota: "))

if nota == 0:
  print("Você falhou a atividade.")
elif nota >= 1 and nota <= 5:
  print("Você tirou uma nota abaixo da média.")
elif nota >= 6 and nota <= 9:
  print("Você tirou uma nota acima da média.")
elif nota == 10:
  print("Você tirou a nota máxima!")
else:
  print("Nota inválida.")