# -*- coding: utf-8 -*-
"""Conheça o Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

valor = int(input("Digite o valor da compra: "))
vip = bool(input("É um cliente VIP? (True/False): "))

if valor >= 100 or vip == True:
  print("Você pode ter a compra com frete grátis")
else:
  print("Você irá pagar o valor cm frete.")