# -*- coding: utf-8 -*-
"""Conheça o Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

velocidade = int(input("Digite a velocidade do seu carro: "))

if velocidade > 80:
  print("Velocidade muito alta!")
elif velocidade <= 80:
  print("Sua velocidade está dentro do limite, parabéns.")